<a href="https://colab.research.google.com/github/evehling/Data-Science/blob/master/Neural_Net_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Neural Net Skeleton

In [0]:
import numpy as np

def sigmoid(x):
  return 1.0/(1+ np.exp(-x))
#define sigmoid curve 1/(1+e^-x); use numpy's exponent function

def sigmoid_derivative(x):
  return x * (1.0 -x)
#define sigmoid derivative function

class NeuralNetwork:
  def __init__(self,x,y):
#define 2 attributes, x (the input values) and y (the expected output)
    self.input = x
 #define first set of weights--initially they are randomly chosen
    self.weights1 = np.random.rand(self.input.shape[1],4)
    self.weights2 = np.random.rand(4,1)
    self.y = y
    self.output = np.zeros(self.y.shape)
 #returns an array with self.y.shape 
   
  def feedforward(self):
 #apply the sigmoid function to the results of matrix multiplication of X (the array of 0 and 1) and weights
      self.layer1 = sigmoid(np.dot(self.input, self.weights1))
 #apply sigmoid function to the matrix multiplication of the above results and the second set of weights
      self.output = sigmoid(np.dot(self.layer1, self.weights2))
  
  def backprop(self):
  #to calculate second set of weights, multiply error by the sigmoid derivative of the output from above
  #the multiplying by 2 of the error calc is bc of the the way you derive the sigmoid function
    d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
    #matrix multiplication of layer 1 X (2* error calc * derivative of hidden layer output)
 
    d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y - self.output)* sigmoid_derivative(self.output), self.weights2.T)* 
                                      sigmoid_derivative(self.layer1)))
    
 #the np.dot creates an array of the weights (that we can see in the output cell)

    #update weights with matrix multiplication that we did in calculation d_weights 1 & 2
    
    self.weights1 += d_weights1
    self.weights2 += d_weights2
    
if __name__ == "__main__":
  #inputs/training data in an array
  X = np.array([[0,0,1],
               [0,1,1],
               [1,0,1],
               [1,1,1]])
  #the expected y outcomes for training data
  y= np.array([[0], [1], [1], [0]])
  #create new NeuralNetwork object using array and expected outputs
  nn = NeuralNetwork(X,y)
  
  #for integers in range 0-10,000 run through feedforward() and backprop() methods 
  for i in range(50000):
    #iterate these two functions in range^^
    nn.feedforward()
    nn.backprop()
    
  print(nn.weights1)
  print(nn.weights2)
  print(nn.output)



[[ 7.2286654   5.41424057  0.11755715  3.87443952]
 [ 7.3828378   5.19532697  0.60381793  4.06314229]
 [-3.18934235 -7.99870787  1.83196799 -1.38272154]]
[[ 11.17048373]
 [-13.36106102]
 [ -7.85947311]
 [  2.91076883]]
[[0.00316167]
 [0.99678937]
 [0.99712289]
 [0.00346493]]
